#Sale prediction Project

Importing the Libraries

In [ ]:
import pandas as pd
import numpy as np

uploading the dataset files

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving cardb_ds.csv to cardb_ds.csv


Analysing The Dataset

In [ ]:
dataset=pd.read_csv("cardb_ds.csv")
print(dataset)

     Age  AnnualSalary  Purchased
0     35         20000          0
1     40         43500          0
2     49         74000          0
3     40        107500          1
4     25         79000          0
..   ...           ...        ...
995   38         59000          0
996   47         23500          0
997   28        138500          1
998   48        134000          1
999   44         73500          0

[1000 rows x 3 columns]


Testing some cases

In [ ]:
print(dataset.shape)
print(dataset.head(10))
print(dataset.tail(20))

(1000, 3)
   Age  AnnualSalary  Purchased
0   35         20000          0
1   40         43500          0
2   49         74000          0
3   40        107500          1
4   25         79000          0
5   47         33500          1
6   46        132500          1
7   42         64000          0
8   30         84500          0
9   41         52000          0
     Age  AnnualSalary  Purchased
980   46         23500          1
981   39         79000          0
982   39         60500          0
983   42         54000          0
984   28         87000          0
985   45         77500          0
986   48         33000          1
987   31         71000          0
988   33        121500          1
989   27         84000          0
990   25         56500          0
991   30         48500          0
992   24         67500          0
993   54        136500          0
994   53        104000          1
995   38         59000          0
996   47         23500          0
997   28        138500    

Splitting the input Data

In [ ]:
X= dataset.iloc[:,:-1].values
X

array([[    35,  20000],
       [    40,  43500],
       [    49,  74000],
       ...,
       [    28, 138500],
       [    48, 134000],
       [    44,  73500]])

Splitting the Output data

In [ ]:
Y= dataset.iloc[:,-1].values
Y

array([0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,

Splitting (Train And Test Data)

In [ ]:

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test= train_test_split(X,Y,test_size=0.25,random_state=0)

Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train= sc.fit_transform(X_train)
X_test= sc.transform(X_test)
print(X_train)

[[-1.92084369 -1.50249061]
 [ 0.91133082 -1.35965201]
 [ 1.00573664  1.81136479]
 ...
 [ 1.94979481  0.3258434 ]
 [-0.97678552 -0.31693027]
 [-2.01524951 -0.78829764]]


Algorithm

In [ ]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(X_train,Y_train)

LogisticRegression()

Prediction

In [ ]:
y_pred = model.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),Y_test.reshape(len(Y_test),1)),1))

[[1 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]

Accuracy Score of Our Project

In [50]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(Y_test,y_pred)
print("confusion matrix: ")
print(cm)

print("Accuracy of the model: ",format(accuracy_score(Y_test,y_pred)*100))

confusion matrix: 
[[138  14]
 [ 24  74]]
Accuracy of the model: {0}% 84.8


In [54]:
age=int(input("Enter customer's age: "))
sal=int(input("Enter customer's salary: "))
newCust=[[age,sal]]
result=model.predict(sc.transform(newCust))
print(result)
if result==1:
  print("Customer will buy")
else:
  print("Customer will not buy")

Enter customer's age: 19
Enter customer's salary: 35000
[0]
Customer will not buy
